import type { Metadata } from "next";
import "./globals.css";
import { pretendard } from "@/app/fonts";
import MainHeader from "@/components/main-header/main-header";

import Providers from "@/app/providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${pretendard.variable} font-sans antialiased`}>
        <Providers>
          <div className="min-h-screen max-w-[1680px] mx-auto px-10 overflow-x-hidden">
            <MainHeader /> {/* 여기서는 px-10 안 써도 이미 감싸짐 */}
            <main>{children}</main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
