import type { Metadata } from "next";
import "./globals.css";
import { pretendard } from "@/app/fonts";
import MainHeader from "@/components/main-header/main-header";

import Providers from "@/app/providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`max-w-[1680px] mx-auto ${pretendard.variable} font-sans antialiased px-10`}
      >
        <Providers>
          <MainHeader />
          {children}
        </Providers>
      </body>
    </html>
  );
}
